const header=document.querySelector('.site-header');
const menuButton=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});
menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');document.body.classList.toggle('menu-open',open);menuButton.setAttribute('aria-expanded',open);menuButton.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню')});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menuButton?.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});
document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min((i%4)*70,210)}ms`;observer.observe(el)});
document.querySelectorAll('.day-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.day-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});document.querySelectorAll('.timeline').forEach(panel=>{panel.classList.remove('active');panel.hidden=true});tab.classList.add('active');tab.setAttribute('aria-selected','true');const panel=document.getElementById(tab.dataset.day);panel.hidden=false;requestAnimationFrame(()=>panel.classList.add('active'))}));
document.querySelectorAll('.choose-package').forEach(btn=>btn.addEventListener('click',()=>{document.getElementById('package-select').value=btn.dataset.package;document.getElementById('booking').scrollIntoView({behavior:reduceMotion?'auto':'smooth'})}));
document.querySelectorAll('.flip-card').forEach(card=>{card.addEventListener('click',()=>card.classList.toggle('is-flipped'));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();card.classList.toggle('is-flipped')}})});
const sharingNote=document.querySelector('.sharing-note');
if(sharingNote){const sharingObserver=new IntersectionObserver(entries=>entries.forEach(entry=>sharingNote.classList.toggle('is-focused',entry.isIntersecting)),{threshold:.45});sharingObserver.observe(sharingNote)}
const karaoke=document.querySelector('.karaoke');
if(karaoke){const words=[...karaoke.querySelectorAll('span')];const karaokeObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){words.forEach((word,index)=>setTimeout(()=>word.classList.add('lit'),index*140));karaokeObserver.disconnect()}}),{threshold:.45});karaokeObserver.observe(karaoke)}
if(!reduceMotion){const heroMedia=document.querySelector('[data-parallax]');const glow=document.querySelector('.cursor-glow');const dot=document.querySelector('.cursor-dot');const scene=document.querySelector('.scene-3d');let ticking=false;window.addEventListener('scroll',()=>{if(scrollY<innerHeight*1.2)heroMedia.style.transform=`translate3d(0,${scrollY*.12}px,0) scale(1.02)`;if(sharingNote){const rect=sharingNote.getBoundingClientRect();const proximity=Math.max(0,1-Math.abs(rect.top+rect.height/2-innerHeight/2)/(innerHeight*.8));sharingNote.style.transform=`scale(${.96+proximity*.055})`}},{passive:true});window.addEventListener('pointermove',e=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{glow.style.opacity='1';glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';if(scene&&scrollY<innerHeight){const rx=(e.clientY/innerHeight-.5)*-5;const ry=(e.clientX/innerWidth-.5)*8;scene.style.transform=`rotateX(${rx}deg) rotateY(${ry}deg)`}ticking=false})},{passive:true});document.querySelectorAll('a,button,input,select,summary').forEach(el=>{el.addEventListener('mouseenter',()=>dot.classList.add('active'));el.addEventListener('mouseleave',()=>dot.classList.remove('active'))})}
